name = "ReuseDistance"
uuid = "ab64822e-348e-4aa5-8a6d-5df15d5e7b8c"
authors = ["Mark Hildebrand <mhildebrand@ucdavis.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
